### ISSUE TITLE
Deleting widget leaves broken menu item

### ISSUE THREAD

**Issue by mikehatfield** [mattrabe/Widgets-In-Menu-for-WordPress#4]
Deleting a menu widget from widgets in menu removes the widget.  However the reference to that widget in the menu remains.  Leaving a broken active menu item in the navigation.

**Comment by mattrabe** [comment]
Moved to https://bitbucket.org/campcreative/bayalarm2016/issues/3/deleting-widget-leaves-broken-menu-item
